# Generated by Django 3.2.8 on 2021-11-07 15:03

import Tree.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tree.department', verbose_name='父部门')),
            ],
            options={
                'verbose_name': '树',
                'verbose_name_plural': '树',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', mdeditor.fields.MDTextField(default='', verbose_name='正文')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to=settings.AUTH_USER_MODEL, verbose_name='回答者')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node', to='Tree.department', verbose_name='节点')),
            ],
            options={
                'verbose_name': '节点',
                'verbose_name_plural': '节点',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='NodeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(default='', null=True, upload_to=Tree.models.get_file_upload_path, verbose_name='文件路径')),
                ('File_name', models.CharField(default='', max_length=128, null=True, verbose_name='文件名')),
                ('department', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file', to='Tree.department', verbose_name='节点')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='Tree.node')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='tags',
            field=models.ManyToManyField(blank=True, to='Tree.Tag', verbose_name='标签'),
        ),
    ]
