# Generated by Django 3.2.8 on 2021-11-09 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tree', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '路径树', 'verbose_name_plural': '路径树'},
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'verbose_name': '叶子节点', 'verbose_name_plural': '叶子节点'},
        ),
        migrations.AlterModelOptions(
            name='nodefile',
            options={'verbose_name': '上传文件', 'verbose_name_plural': '上传文件'},
        ),
    ]
